import Girth

#print axioms StructuralRamsey.Girth.aStrong_univ
#print axioms StructuralRamsey.Girth.sameCopy_of_range_subset
#print axioms StructuralRamsey.Girth.girthGT_mono
#print axioms StructuralRamsey.Girth.girthGT_one
#print axioms StructuralRamsey.Girth.girthGT_of_subset
#print axioms StructuralRamsey.Girth.pairwise_subsingleton_of_girthGT_two
#print axioms StructuralRamsey.Girth.aLinear_of_girthGT_two
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.toTreeAmalgam
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.irreducible_contained_in_copy
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.aCopy_contained_in_copy
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.bCopy_same_constituent
#print axioms StructuralRamsey.Girth.freeAmalgam_side_intersection
#print axioms StructuralRamsey.Girth.irreducibleCopy_side_of_freeAmalgam
#print axioms StructuralRamsey.Girth.sameCopy_comp
#print axioms StructuralRamsey.Girth.controlledIntersection_comp
#print axioms StructuralRamsey.Girth.crossControlled_glueA
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.aCopiesCoveredByB
#print axioms StructuralRamsey.Girth.sameCopy_of_contained_and_not_subsingleton
#print axioms StructuralRamsey.Girth.aLinear_of_base_and_controlled
#print axioms StructuralRamsey.Girth.aStrong_of_linear_and_controlled
#print axioms StructuralRamsey.Girth.localTreeRamseyCore
