import Girth

#print axioms StructuralRamsey.Girth.aStrong_univ
#print axioms StructuralRamsey.Girth.sameCopy_of_range_subset
#print axioms StructuralRamsey.Girth.girthGT_mono
#print axioms StructuralRamsey.Girth.girthGT_one
#print axioms StructuralRamsey.Girth.girthGT_of_subset
#print axioms StructuralRamsey.Girth.girthGT_mappedSupportCopies
#print axioms StructuralRamsey.Girth.cyclicSucc_eq_finRotate
#print axioms StructuralRamsey.Girth.exists_cyclic_change_of_nonconstant
#print axioms StructuralRamsey.Girth.exists_first_cyclic_change
#print axioms StructuralRamsey.Girth.BergePath.initialSegment
#print axioms StructuralRamsey.Girth.BergePath.close
#print axioms StructuralRamsey.Girth.BergeCycle.cyclicPath
#print axioms StructuralRamsey.Girth.pairwise_subsingleton_of_girthGT_two
#print axioms StructuralRamsey.Girth.aLinear_of_girthGT_two
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.toTreeAmalgam
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.irreducible_contained_in_copy
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.aCopy_contained_in_copy
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.bCopy_same_constituent
#print axioms StructuralRamsey.Girth.freeAmalgam_side_intersection
#print axioms StructuralRamsey.Girth.irreducibleCopy_side_of_freeAmalgam
#print axioms StructuralRamsey.Girth.sameCopy_comp
#print axioms StructuralRamsey.Girth.controlledIntersection_comp
#print axioms StructuralRamsey.Girth.controlledPair_congr
#print axioms StructuralRamsey.Girth.controlledPair_swap
#print axioms StructuralRamsey.Girth.crossControlled_glueA
#print axioms StructuralRamsey.Girth.crossSubsingleton_gluePoint
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.bIntersectionsControlled
#print axioms StructuralRamsey.Girth.intersectionSubsingleton_congr
#print axioms StructuralRamsey.Girth.intersectionMem_congr
#print axioms StructuralRamsey.Girth.vertexSupported_comp
#print axioms StructuralRamsey.Girth.vertexSupported_congr
#print axioms StructuralRamsey.Girth.singletonSupport_congr
#print axioms StructuralRamsey.Girth.vertexSupported_of_common_ACopy
#print axioms StructuralRamsey.Girth.singletonIntersectionsSupported_comp
#print axioms StructuralRamsey.Girth.crossSingletonSupport_glueA
#print axioms StructuralRamsey.Girth.crossSingletonSupport_gluePoint
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.singletonIntersectionsSupported
#print axioms StructuralRamsey.Girth.allowedIntersection_symm
#print axioms StructuralRamsey.Girth.JoinTree.occurrence_reachable
#print axioms StructuralRamsey.Girth.ForestOfCopies.joinTree_of_nonempty
#print axioms StructuralRamsey.Girth.JoinTree.mem_parent_of_mem_leaf_and_other
#print axioms StructuralRamsey.Girth.JoinTree.leaf_inter_iUnion_eq_parent
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.aCopiesCoveredByB
#print axioms StructuralRamsey.Girth.sameCopy_of_contained_and_not_subsingleton
#print axioms StructuralRamsey.Girth.aLinear_of_base_and_controlled
#print axioms StructuralRamsey.Girth.aStrong_of_linear_and_controlled
#print axioms StructuralRamsey.Girth.localTreeRamseyCore

#print axioms StructuralRamsey.Girth.girthGT_union_of_subsingleton_glue

#print axioms StructuralRamsey.Girth.cyclicRunIndex_ne_before
#print axioms StructuralRamsey.Girth.BergePath.ofEdgeMem
#print axioms StructuralRamsey.Girth.BergeCycle.cyclicPath_vertex_last

#print axioms StructuralRamsey.Girth.exists_cyclic_run_to_change
#print axioms StructuralRamsey.Girth.exists_false_cyclic_run

#print axioms StructuralRamsey.Girth.girthGT_union_of_edge_glue

#print axioms StructuralRamsey.Girth.freeAmalgam_overlap_carrier_eq
#print axioms StructuralRamsey.Girth.supportCopies_eq_union_mapped_of_freeAmalgam
#print axioms StructuralRamsey.Girth.mappedSupport_cross_subset_overlap
#print axioms StructuralRamsey.Girth.punit_overlap_subsingleton
#print axioms StructuralRamsey.Girth.supportCopies_eq_mapped_of_iso
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.girthGT

#print axioms StructuralRamsey.Girth.JoinTree.exists_leaf_attachment

#print axioms StructuralRamsey.Girth.sameCopy_of_common_distinct_pair
#print axioms StructuralRamsey.Girth.targetClosed_univ
#print axioms StructuralRamsey.Girth.targetClosed_singleton
#print axioms StructuralRamsey.Girth.targetClosed_copy
#print axioms StructuralRamsey.Girth.targetClosed_of_distinct_pair
#print axioms StructuralRamsey.Girth.targetClosed_classify
#print axioms StructuralRamsey.Girth.targetClosed_classify_nonempty

#print axioms StructuralRamsey.Girth.pairClosed_iff_aStrong

#print axioms StructuralRamsey.Girth.controlledIntersection_of_targetClosedPullback
#print axioms StructuralRamsey.Girth.bIntersectionsControlled_of_targetClosedPullbacks
#print axioms StructuralRamsey.Girth.bCopiesStrong_of_pairClosed
#print axioms StructuralRamsey.Girth.closedTargetCopies_geometry

#print axioms StructuralRamsey.Girth.elementaryClosure_isClosed_iff_pairClosed
#print axioms StructuralRamsey.Girth.elementaryClosure_isClosed_iff_aStrong
#print axioms StructuralRamsey.Girth.targetClosure_isClosed_iff
#print axioms StructuralRamsey.Girth.targetClosure_closed_classify_nonempty

#print axioms StructuralRamsey.Girth.structureEmbedding_range_isClosed
#print axioms StructuralRamsey.Girth.structureIsClosed_inter
#print axioms StructuralRamsey.Girth.structureIsClosed_preimage
#print axioms StructuralRamsey.Girth.targetEmbedding_range_pairClosed
#print axioms StructuralRamsey.Girth.targetEmbedding_range_aStrong
#print axioms StructuralRamsey.Girth.targetEmbedding_pullback_targetClosed
#print axioms StructuralRamsey.Girth.targetEmbeddings_controlledIntersection

#print axioms StructuralRamsey.Girth.targetClosureLift

#print axioms StructuralRamsey.Girth.elementaryClosureEmbeddingOfStrong
#print axioms StructuralRamsey.Girth.freeAmalgam_left_aStrong
#print axioms StructuralRamsey.Girth.freeAmalgam_right_aStrong
#print axioms StructuralRamsey.Girth.aLinear_of_freeAmalgam
#print axioms StructuralRamsey.Girth.concreteElementaryClosureAmalgam_geometry
#print axioms StructuralRamsey.Girth.elementaryClosure_isFreeAmalgam
#print axioms StructuralRamsey.Girth.concreteElementaryClosure_freeAmalgam
#print axioms StructuralRamsey.Girth.sameCopy_of_comp
#print axioms StructuralRamsey.Girth.ordered_embedding_eq_of_sameCopy
#print axioms StructuralRamsey.Girth.aLinear_induce
#print axioms StructuralRamsey.Girth.elementaryClosure_induceEmbedding
#print axioms StructuralRamsey.Girth.elementaryClosure_closed_induce_aLinear
#print axioms StructuralRamsey.Girth.pieceListEdges_subset_carrier
#print axioms StructuralRamsey.Girth.girthGT_pieceList_of_singletonAttachments
#print axioms StructuralRamsey.Girth.JoinTree.leaf_inter_rest_subsingleton
#print axioms StructuralRamsey.Girth.elementaryEmbedding_range_aStrong
#print axioms StructuralRamsey.Girth.elementaryClosure_freeAmalgam_of_embeddings
#print axioms StructuralRamsey.Girth.girthGT_of_edgeFamily_subsingleton
#print axioms StructuralRamsey.Girth.oneEdgePiece_girthGT
#print axioms StructuralRamsey.Girth.girthGT_oneEdgeList_of_singletonAttachments
#print axioms StructuralRamsey.Girth.bergeTriangle_of_three_pair_edges
#print axioms StructuralRamsey.Girth.three_pair_edges_not_all_distinct
#print axioms StructuralRamsey.Girth.pairCovered_subset_edge_of_girthGT_three
#print axioms StructuralRamsey.Girth.irreducible_induce_subset_edge_of_girthGT_three
#print axioms StructuralRamsey.Girth.supportCopies_eq_of_decorated_cover
#print axioms StructuralRamsey.Girth.decorated_highGirth_support_exact
#print axioms StructuralRamsey.Girth.closureFreeAmalgamRel
#print axioms StructuralRamsey.Girth.aLinear_of_embedding
#print axioms StructuralRamsey.Girth.closureEmbedding_range_aStrong
#print axioms StructuralRamsey.Girth.hasElementaryCA_of_embedding
#print axioms StructuralRamsey.Girth.targetClosure_mem_ElementaryCAClass
#print axioms StructuralRamsey.Girth.closureLanguage_positiveFuncArity
#print axioms StructuralRamsey.Girth.ElementaryCAClass_freeAmalgamationClass
#print axioms StructuralRamsey.Girth.structureEmbeddingWithLinearOrder
#print axioms StructuralRamsey.Girth.ClosedTargetRamseyFamily.arrow
#print axioms StructuralRamsey.Girth.closedTargetRamseyFamily_of_monotone_embeddings
#print axioms StructuralRamsey.Girth.closedTargetRamseyFamily_ordered
#print axioms StructuralRamsey.Girth.aLinearRamsey_of_monotone_embeddings
#print axioms StructuralRamsey.Girth.aLinearRamsey_ordered
#print axioms StructuralRamsey.Girth.EdgeTransversal.edge_eq_range_vertex
#print axioms StructuralRamsey.Girth.decorateSupport_relationsCovered
#print axioms StructuralRamsey.Girth.decorateSupport_edgeCarrier
#print axioms StructuralRamsey.Girth.decorateSupportSystem
#print axioms StructuralRamsey.Girth.decorateSupportSystem_edgeEmbedding
#print axioms StructuralRamsey.Girth.decorateSupportSystemEmbedding
#print axioms StructuralRamsey.Girth.decorateSupportSystem_embeddingEquivEdge
#print axioms StructuralRamsey.Girth.StrongSupportEmbedding.mapEdge
#print axioms StructuralRamsey.Girth.copyCarrier_comp_decorateSupportSystemEmbedding
#print axioms StructuralRamsey.Girth.strongSupportRamseyFamily_partiteArrow
#print axioms StructuralRamsey.Girth.structuralPartiteWitness_of_strongSupportRamsey
#print axioms StructuralRamsey.Girth.decorateSupport_exact
#print axioms StructuralRamsey.Girth.decorateSupportEmbedding
#print axioms StructuralRamsey.Girth.decorateSupport_ordered_copy_eq_edgeEmbedding
#print axioms StructuralRamsey.Girth.decorateSupport_ordered_embeddingEquivEdge
#print axioms StructuralRamsey.Girth.decorateSupportEmbedding_range_aStrong
#print axioms StructuralRamsey.Girth.decorateSupportEmbedding_range_aStrong_of_highGirth
#print axioms StructuralRamsey.Girth.decorateStrongSupportCopy_of_highGirth

#print axioms StructuralRamsey.Girth.customInducedPictureStep

#print axioms StructuralRamsey.Girth.activeInduceProjected
#print axioms StructuralRamsey.Girth.activeAttachment_copy_comp
#print axioms StructuralRamsey.Girth.activeAttachment_pictureProperty
#print axioms StructuralRamsey.Girth.activeInducedPictureStep
#print axioms StructuralRamsey.Girth.activeCarrier
#print axioms StructuralRamsey.Girth.projected_mem_activeCarrier
#print axioms StructuralRamsey.Girth.activeCarrier_subset_support
#print axioms StructuralRamsey.Girth.activeInducedPictureStep_onActiveCarrier

#print axioms StructuralRamsey.Girth.irreduciblesExtendTo_partiteAttachment
#print axioms StructuralRamsey.Girth.attachment_copy_core_intersection
#print axioms StructuralRamsey.Girth.attachment_copy_copy_intersection
#print axioms StructuralRamsey.Girth.attachment_copy_copy_intersection_subset_core
#print axioms StructuralRamsey.Girth.attachment_irreducible_copy_localize
#print axioms StructuralRamsey.Girth.attachment_core_aStrong
#print axioms StructuralRamsey.Girth.attachment_copy_aStrong
#print axioms StructuralRamsey.Girth.attachment_aLinear
#print axioms StructuralRamsey.Girth.shared_standard_copy_preimage_mem_glue
#print axioms StructuralRamsey.Girth.shared_standard_copy_part_mem_active_support
#print axioms StructuralRamsey.Girth.shared_standard_copy_part_mem_base_intersection
#print axioms StructuralRamsey.Girth.no_common_projected_copy_of_subsingleton_base_intersection
#print axioms StructuralRamsey.Girth.no_common_projected_copy_of_base_aLinear
#print axioms StructuralRamsey.Girth.activePictureStep_invariants
#print axioms StructuralRamsey.Girth.DesignatedCopy.projects
#print axioms StructuralRamsey.Girth.activeCarrier_part_in_baseCopy
#print axioms StructuralRamsey.Girth.activeSubsystem_aGenerated
#print axioms StructuralRamsey.Girth.DesignatedCopy.transportToStandard
#print axioms StructuralRamsey.Girth.designatedCoversIrreducibles_partiteAttachment
#print axioms StructuralRamsey.Girth.transportedDesignated_corePoint_supported
#print axioms StructuralRamsey.Girth.initialDesignatedCopy
#print axioms StructuralRamsey.Girth.initial_designatedCoversIrreducibles
#print axioms StructuralRamsey.Girth.localIrreduciblesCovered_of_extendTo_and_ACopyCover
#print axioms StructuralRamsey.Girth.decorateSupport_irreduciblesExtendTo
#print axioms StructuralRamsey.Girth.localForest_ACopiesCovered
#print axioms StructuralRamsey.Girth.localForest_localIrreduciblesCovered

#print axioms StructuralRamsey.Girth.HypergraphPiece.carrier_subset_of_isOneEdge_of_allowed_not_subsingleton
#print axioms StructuralRamsey.Girth.HypergraphPiece.isOneEdge_allowed_dichotomy

#print axioms StructuralRamsey.Girth.JoinTree.degree_eq_one_of_unique_neighbor
#print axioms StructuralRamsey.Girth.JoinTree.pairwiseAllowed_erase
#print axioms StructuralRamsey.Girth.ForestOfCopies.erase_leaf

#print axioms StructuralRamsey.Girth.JoinTree.mem_center_of_shared_not_reachable_after_delete

#print axioms StructuralRamsey.Girth.JoinTree.intersection_subsingleton_across_delete_of_oneEdge_of_no_full

#print axioms StructuralRamsey.Girth.JoinTree.neighbor_eq_of_reachable_after_delete

#print axioms StructuralRamsey.Girth.JoinTree.mem_root_of_mem_center_and_reachable_after_delete

#print axioms StructuralRamsey.Girth.JoinTree.shared_mem_component_roots

#print axioms StructuralRamsey.Girth.JoinTree.exists_neighbor_reachable_after_delete

#print axioms StructuralRamsey.Girth.exists_tree_fibers_preconnected

#print axioms StructuralRamsey.Girth.isTree_of_connected_card_edgeFinset

#print axioms StructuralRamsey.Girth.isTree_of_connected_ncard_edgeSet
#print axioms StructuralRamsey.Girth.JoinTree.rewireAfterDelete_isTree
#print axioms StructuralRamsey.Girth.JoinTree.reachable_occurrence_after_delete_of_not_mem_center
#print axioms StructuralRamsey.Girth.JoinTree.neighborAttachment_subsingleton
#print axioms StructuralRamsey.Girth.JoinTree.neighborAttachment_eq_of_common
#print axioms StructuralRamsey.Girth.JoinTree.nonempty_eraseOneEdgeNoFull
#print axioms StructuralRamsey.Girth.ForestOfCopies.erase_oneEdge_of_no_full
#print axioms StructuralRamsey.Girth.starGraph_induce_preconnected_of_mem_center
#print axioms StructuralRamsey.Girth.JoinTree.nonempty_eraseMember_of_full

#print axioms StructuralRamsey.Girth.JoinTree.fullOccurrence_preconnected
#print axioms StructuralRamsey.Girth.JoinTree.enlargeCarriers

#print axioms StructuralRamsey.Girth.pointAtEmbedding
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.exists_freeGlueA
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.exists_freeGluePoint
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.exists_freeGluePointAt
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.exists_disjointCopyExtension

#print axioms StructuralRamsey.Girth.induceEmbeddingOfSubset
#print axioms StructuralRamsey.Girth.induceUnion_isFreeAmalgam
#print axioms StructuralRamsey.Girth.induceUnion_isFreeAmalgam_of_overlap
#print axioms StructuralRamsey.Girth.freeAmalgam_liftEmbedding_sameOverlap

#print axioms StructuralRamsey.Girth.familyMemberEmbedding
#print axioms StructuralRamsey.Girth.supportedBCopyOverlap_symm
#print axioms StructuralRamsey.Girth.BCopyJoinTree.leaf_inter_rest_eq_parent
#print axioms StructuralRamsey.Girth.pairwiseSupportedBCopyOverlap_erase
#print axioms StructuralRamsey.Girth.BCopyJoinTree.restToFullEmbedding

#print axioms StructuralRamsey.Girth.BCopyJoinTree.familyUnion_isFreeAmalgam_leaf_of_overlap

#print axioms StructuralRamsey.Girth.aCopyToFamilyUnion
#print axioms StructuralRamsey.Girth.aCopyFactorIntoMember
#print axioms StructuralRamsey.Girth.ambientPointEmbedding

#print axioms StructuralRamsey.Girth.aCopyFactorIntoMember_spec

#print axioms StructuralRamsey.Girth.aCopyFactorIntoMember_exists

#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.extendCopyForestLeaf_overA
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.exists_disjointCopyExtension_split
#print axioms StructuralRamsey.Girth.inducedImageUnion_isFreeAmalgam_of_disjoint
#print axioms StructuralRamsey.Girth.ambientEmptyToMember
#print axioms StructuralRamsey.Girth.ambientEmptyToFamilyUnion
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.extendCopyForestLeaf_overPoint
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.extendCopyForestLeaf_overEmpty
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.extendCopyForestLeaf
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.exists_aEmbedding
#print axioms StructuralRamsey.Girth.familyUnionToMember_of_subsingleton
#print axioms StructuralRamsey.Girth.bCopyForest_embeds_supportedTree
#print axioms StructuralRamsey.Girth.bSupportPiece
#print axioms StructuralRamsey.Girth.supportJoinTreeToBCopyJoinTree
#print axioms StructuralRamsey.Girth.pairwiseSupportedBCopyOverlap_of_supportAllowed
#print axioms StructuralRamsey.Girth.supportForestOfBCopies_embeds_supportedTree
#print axioms StructuralRamsey.Girth.ABMember.supportEdge_witness
#print axioms StructuralRamsey.Girth.pairwiseMixedSharedVerticesSupported_erase
#print axioms StructuralRamsey.Girth.mixedMemberEmbedding
#print axioms StructuralRamsey.Girth.aCopyFactorIntoMixedMember
#print axioms StructuralRamsey.Girth.mixedFamilyUnionToMember_of_subsingleton
#print axioms StructuralRamsey.Girth.JoinTree.mixed_leaf_inter_rest_eq_parent
#print axioms StructuralRamsey.Girth.JoinTree.mixedRestToFullEmbedding
#print axioms StructuralRamsey.Girth.JoinTree.mixedFamilyUnion_isFreeAmalgam_leaf_of_overlap
#print axioms StructuralRamsey.Girth.ASupportedTreeAmalgam.extendMixedForestLeaf
#print axioms StructuralRamsey.Girth.mixedJoinTree_embeds_supportedTree
#print axioms StructuralRamsey.Girth.mixedForest_embeds_supportedTree
#print axioms StructuralRamsey.Girth.girthGT_carrierEdgeFamily_of_joinTree
#print axioms StructuralRamsey.Girth.pairwiseMixedSharedVerticesSupported_of_bMembers
#print axioms StructuralRamsey.Girth.mixedForest_embeds_supportedTree_of_bMemberSupport
#print axioms StructuralRamsey.Girth.JoinTree.restrictCarriers
#print axioms StructuralRamsey.Girth.pairwise_restrictedCarrier_subsingleton_of_allowed
#print axioms StructuralRamsey.Girth.girthGT_restrictedCarrierEdgeFamily_of_forest
#print axioms StructuralRamsey.Girth.girthGT_restrictedCarrierEdgeFamily_of_part
#print axioms StructuralRamsey.Girth.girthGT_forest_restricted_to_part
#print axioms StructuralRamsey.Girth.transportedDesignated_sharedACopy_supported
#print axioms StructuralRamsey.Girth.transportedDesignated_sharedDesignated_supported
#print axioms StructuralRamsey.Girth.transportedDesignated_sharedSupport
#print axioms StructuralRamsey.Girth.forest_centerWithEdgeLeaves
#print axioms StructuralRamsey.Girth.forest_bSupport_with_aLeaves
#print axioms StructuralRamsey.Girth.pairwiseAllowed_reindex
#print axioms StructuralRamsey.Girth.ForestOfCopies.reindex
#print axioms StructuralRamsey.Girth.isTree_sum_sup_edge
#print axioms StructuralRamsey.Girth.JoinTree.sumBridge
#print axioms StructuralRamsey.Girth.pairwiseAllowed_sumPieces
#print axioms StructuralRamsey.Girth.forestOfCopies_sumBridge
#print axioms StructuralRamsey.Girth.initialACopy_same_index
#print axioms StructuralRamsey.Girth.initialACopy_factors_component
#print axioms StructuralRamsey.Girth.sigmaSplitAt
#print axioms StructuralRamsey.Girth.joinTree_sigma_of_subsingleton
#print axioms StructuralRamsey.Girth.joinTree_lift_local
#print axioms StructuralRamsey.Girth.forestOfCopies_lift_local
#print axioms StructuralRamsey.Girth.pairwiseAllowed_of_disjoint
#print axioms StructuralRamsey.Girth.joinTree_of_disjoint
#print axioms StructuralRamsey.Girth.forestOfCopies_of_disjoint
#print axioms StructuralRamsey.Girth.forestOfCopies_lift_disjoint
#print axioms StructuralRamsey.Girth.JoinTree.mem_snd_of_mem_endpoints
#print axioms StructuralRamsey.Girth.JoinTree.first_separator_edge_eq
#print axioms StructuralRamsey.Girth.localMember_contains_outer_edge
#print axioms StructuralRamsey.Girth.crossAllowed_of_linear_outer
#print axioms StructuralRamsey.Girth.forestOfCopies_lift_local_of_linear
#print axioms StructuralRamsey.Girth.sameCopy_comp_of_sameCopy
#print axioms StructuralRamsey.Girth.initialPicture_aLinear
#print axioms StructuralRamsey.Girth.initialACopyOwner
#print axioms StructuralRamsey.Girth.initialACopyFactor
#print axioms StructuralRamsey.Girth.initialPicture_forestCompletion
#print axioms StructuralRamsey.Girth.boundaryIncidenceColoring
#print axioms StructuralRamsey.Girth.boundaryIncidence_closedWalk_even
#print axioms StructuralRamsey.Girth.boundaryIncidence_cycle_even
#print axioms StructuralRamsey.Girth.boundaryIncidence_getVert_even_left
#print axioms StructuralRamsey.Girth.boundaryIncidence_getVert_odd_right
#print axioms StructuralRamsey.Girth.bergeCycleOfBoundaryIncidenceCycleLeft
#print axioms StructuralRamsey.Girth.BergeCycle.length_le_card_range
#print axioms StructuralRamsey.Girth.boundaryIncidenceGraph_isAcyclic_of_girthGT
#print axioms StructuralRamsey.Girth.rankedParentGraph_reachable_root
#print axioms StructuralRamsey.Girth.rankedParentGraph_isAcyclic
#print axioms StructuralRamsey.Girth.rankedParentGraph_isTree

#print axioms StructuralRamsey.Girth.activeBoundaryIncidence_isAcyclic
#print axioms StructuralRamsey.Girth.boundaryIncidenceCompletion_connected
#print axioms StructuralRamsey.Girth.exists_boundaryIncidenceCompletionTree

#print axioms StructuralRamsey.Girth.joinTree_singlePiece
#print axioms StructuralRamsey.Girth.pairwiseAllowed_singlePiece
#print axioms StructuralRamsey.Girth.forestOfCopies_attach_dominated
#print axioms StructuralRamsey.Girth.forestOfCopies_attach_disjoint
#print axioms StructuralRamsey.Girth.no_dominating_member_of_not_forest
#print axioms StructuralRamsey.Girth.exists_dominating_member_of_comparable
#print axioms StructuralRamsey.Girth.exists_incomparable_intersections_of_not_forest
#print axioms StructuralRamsey.Girth.not_allowedIntersection_of_contains_incomparable_uncovered
#print axioms StructuralRamsey.Girth.exists_edge_cover_of_allowed_contains_incomparable
#print axioms StructuralRamsey.Girth.LinearEdgeSet
#print axioms StructuralRamsey.Girth.edge_eq_of_contains_incomparable

#print axioms StructuralRamsey.Girth.ownerFiber_card_add_degree_le

#print axioms StructuralRamsey.Girth.bergeCycleOfBoundaryIncidenceCycleLeft_of_pairwiseSubsingleton
#print axioms StructuralRamsey.Girth.bergeCycleOfBoundaryIncidenceCycle_of_pairwiseSubsingleton
#print axioms StructuralRamsey.Girth.boundaryIncidenceGraph_isAcyclic_of_pairwiseSubsingleton_of_girthGT
#print axioms StructuralRamsey.Girth.boundaryIncidenceGraph_isAcyclic_of_forest_restriction
#print axioms StructuralRamsey.Girth.boundaryIncidenceGraph_isAcyclic_of_forest_part
#print axioms StructuralRamsey.Girth.boundaryIncidenceGraph_isAcyclic_of_forest_restricted_to_part
#print axioms StructuralRamsey.Girth.no_boundaryIncidenceCircuit_of_forest_restriction

#print axioms StructuralRamsey.Girth.projectedCopy_activeCarrier_intersection_classify
#print axioms StructuralRamsey.Girth.aStrong_copyCarrier_of_aLinear
#print axioms StructuralRamsey.Girth.projectedACopy_activeCarrier_intersection_classify
#print axioms StructuralRamsey.Girth.attachedProjectedCopy_core_intersection_classify
#print axioms StructuralRamsey.Girth.attachedProjectedACopy_core_intersection_classify

#print axioms StructuralRamsey.Girth.activeCarrier_aStrong_of_base_aLinear
#print axioms StructuralRamsey.Girth.activeCarrier_aStrong_ordered

#print axioms StructuralRamsey.Girth.activeAttachment_geometry_of_base_aLinear
#print axioms StructuralRamsey.Girth.activeAttachment_geometry_ordered
#print axioms StructuralRamsey.Girth.edge_not_subset_of_old_carrier_of_subsingleton_intersection

#print axioms StructuralRamsey.Girth.irreducibleEmbedding_has_standard_owner_of_not_core
#print axioms StructuralRamsey.Girth.projectedCopy_not_subset_core_of_subsingleton_base_intersection
#print axioms StructuralRamsey.Girth.projectedCopy_has_standard_owner_of_subsingleton_base_intersection

#print axioms StructuralRamsey.Girth.supportCopy_mem_mappedSupportCopies_of_subset
#print axioms StructuralRamsey.Girth.bergeCycle_mappedSupportCopies_of_edge_subset
#print axioms StructuralRamsey.Girth.no_short_support_cycle_in_embedding

#print axioms StructuralRamsey.Girth.attachment_shared_point_in_both_local_images
#print axioms StructuralRamsey.Girth.EdgeAntichain
#print axioms StructuralRamsey.Girth.FreshCarrierAlternative
#print axioms StructuralRamsey.Girth.exists_incomparable_fresh_carrier

#print axioms StructuralRamsey.Girth.CyclicIncidenceData.incidenceCircuit_isCircuit
#print axioms StructuralRamsey.Girth.CyclicIncidenceData.no_cyclicIncidenceData_of_acyclic
#print axioms StructuralRamsey.Girth.CyclicIncidenceData.no_cyclicIncidenceData_of_forest_restriction
#print axioms StructuralRamsey.Girth.CyclicIncidenceData.no_cyclicIncidenceData_of_forest_part

#print axioms StructuralRamsey.Girth.CyclicIncidenceData.pullbackImage
#print axioms StructuralRamsey.Girth.CyclicIncidenceData.no_cyclicIncidenceData_of_mapped_forest_restriction
#print axioms StructuralRamsey.Girth.CyclicIncidenceData.no_cyclicIncidenceData_of_mapped_forest_part

#print axioms StructuralRamsey.Girth.untouchedOwner_spec
#print axioms StructuralRamsey.Girth.untouchedOwner_change_shared_point
#print axioms StructuralRamsey.Girth.untouchedOwner_change_shared_point_mapped

#print axioms StructuralRamsey.Girth.forestHistorySMTree
#print axioms StructuralRamsey.Girth.forestHistoryFiniteRamsey

#print axioms StructuralRamsey.Girth.linearEdge_eq_of_two_shared_vertices
#print axioms StructuralRamsey.Girth.no_private_edge_replay_through_two_vertices
#print axioms StructuralRamsey.Girth.private_replay_overlap_classification
#print axioms StructuralRamsey.Girth.no_private_replay_of_nonedge_boundary
#print axioms StructuralRamsey.Girth.forestProfileElimination_of_twoCopyTests
#print axioms StructuralRamsey.Girth.no_linear_amalgam_of_incompatible_pair_owners
#print axioms StructuralRamsey.Girth.linearEdgeSet_union_of_pairClosedOverlap
#print axioms StructuralRamsey.Girth.unique_piece_containing_nonedge_pair
#print axioms StructuralRamsey.Girth.allowedIntersection_of_oneSeparator_boundary
#print axioms StructuralRamsey.Girth.allowedIntersection_oldFamily_of_oneSeparator
#print axioms StructuralRamsey.Girth.pairwiseAllowed_of_common_oneSeparator

#print axioms StructuralRamsey.Girth.RawCyclicIncidenceData.exists_compressed_le
#print axioms StructuralRamsey.Girth.RawCyclicIncidenceData.compress_length_le
#print axioms StructuralRamsey.Girth.RawCyclicIncidenceData.exists_compressed_ofBergeCycle
#print axioms StructuralRamsey.Girth.RawCyclicIncidenceData.no_nonconstant_owner_cycle_of_forest_restriction
#print axioms StructuralRamsey.Girth.RawCyclicIncidenceData.no_nonconstant_owner_cycle_of_forest_part

#print axioms StructuralRamsey.Girth.no_short_support_cycle_of_owner_forest

#print axioms StructuralRamsey.Girth.forestObservableProfile_finite
#print axioms StructuralRamsey.Girth.forestObservableProfile_map_injective

#print axioms StructuralRamsey.Girth.no_short_support_cycle_of_owner_mapped_forest
#print axioms StructuralRamsey.Girth.projectedFactorThroughStandard
#print axioms StructuralRamsey.Girth.projectedFactorThroughStandard_spec
#print axioms StructuralRamsey.Girth.standardActiveEmbedding
#print axioms StructuralRamsey.Girth.projectedCopy_subset_standardActive
#print axioms StructuralRamsey.Girth.no_short_untouched_projected_cycle

#print axioms StructuralRamsey.Girth.ForestOfCopies.erase_finite_oneEdges
