name = "lean-girth"
version = "0.1.0"
defaultTargets = ["Girth"]

[[require]]
name = "partite-construction"
git = "https://github.com/janhubicka/partite-construction.git"
rev = "fde38484dc7d47431244689c6f66ddb4a98d4dd7"

[[lean_lib]]
name = "Girth"
