name = "lean-girth"
version = "0.1.0"
defaultTargets = ["Girth"]

[[require]]
name = "partite-construction"
git = "https://github.com/janhubicka/partite-construction.git"
rev = "3cdbcfae618ffe782cb085db9ab11c7d54762d45"

[[lean_lib]]
name = "Girth"
