import Girth.ActivePicture
import Girth.Support

/-! # Designated copies in a partite picture

The main local-tree induction needs more information than the generic induced
partite invariant: an irreducible substructure is covered by an actual
designated B-copy in the picture, and that copy remembers the B-copy of the
base to which it projects.  This is the data used in the manuscript when
proving that active subsystems are generated by A and when preserving shared
support.
-/

namespace StructuralRamsey.Girth

open StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {UA VB P X : Type v}

/-- A designated B-copy in a P-partite picture, together with its prescribed
base copy. -/
structure DesignatedCopy
    (B : RelStructure L VB)
    (D : RelStructure L P)
    (C : StructuralRamsey.Partite.System L P X)
    (family : Set (RelStructure.Embedding B D)) where
  base : RelStructure.Embedding B D
  base_mem : base ∈ family
  lift : StructuralRamsey.Partite.ProjectedEmbedding B C base

namespace DesignatedCopy

variable {B : RelStructure L VB} {D : RelStructure L P}
variable {C : StructuralRamsey.Partite.System L P X}
variable {family : Set (RelStructure.Embedding B D)}

abbrev embedding (q : DesignatedCopy B D C family) :
    RelStructure.Embedding B C.toRelStructure :=
  q.lift.val

theorem projects (q : DesignatedCopy B D C family) (b : VB) :
    C.part (q.embedding b) = q.base b :=
  q.lift.property b

end DesignatedCopy

/-- Every irreducible substructure of the picture is contained in an actual
designated B-copy. -/
def DesignatedCoversIrreducibles
    (B : RelStructure L VB)
    (D : RelStructure L P)
    (C : StructuralRamsey.Partite.System L P X)
    (family : Set (RelStructure.Embedding B D)) : Prop :=
  ∀ (S : Set X), (C.toRelStructure.induce S).Irreducible →
    ∃ q : DesignatedCopy B D C family,
      ∀ z : S, ∃ b : VB, z.1 = q.embedding b

/-- A relational structure is generated by copies of A when every vertex lies
in an A-copy and every relation tuple is contained in one A-copy. -/
def AGenerated
    (A : RelStructure L UA) (D : RelStructure L X) : Prop :=
  (∀ x : X, ∃ a : RelStructure.Embedding A D, x ∈ copyCarrier a) ∧
  ∀ (R : L.Symbol) (x : Fin (L.arity R) → X), D.rel R x →
    ∃ a : RelStructure.Embedding A D,
      ∀ i, x i ∈ copyCarrier a

/-- Every active vertex projects to a vertex of the prescribed base A-copy. -/
theorem activeCarrier_part_in_baseCopy
    (A : RelStructure L UA)
    (D : RelStructure L P)
    (C : StructuralRamsey.Partite.System L P X)
    (e : RelStructure.Embedding A D)
    {x : X}
    (hx : x ∈ activeCarrier A C e.toFunctionEmbedding) :
    C.part x ∈ copyCarrier e := by
  rcases hx with ⟨a, u, hu⟩
  refine ⟨u, ?_⟩
  have hp := a.property u
  rw [hu] at hp
  exact hp.symm

/-- The active subsystem over a base A-copy is generated by A, provided
irreducibles are covered by designated B-copies whose base images are
A-strong.  This is the manuscript's "processed subsystems are generated by A"
lemma. -/
theorem activeSubsystem_aGenerated
    (A : RelStructure L UA)
    (B : RelStructure L VB)
    (D : RelStructure L P)
    (C : StructuralRamsey.Partite.System L P X)
    (family : Set (RelStructure.Embedding B D))
    (hCover : DesignatedCoversIrreducibles B D C family)
    (hBaseStrong :
      ∀ b : RelStructure.Embedding B D, b ∈ family →
        AStrong A D (copyCarrier b))
    (e : RelStructure.Embedding A D)
    (hActive : (activeCarrier A C e.toFunctionEmbedding).Nonempty) :
    AGenerated A
      (C.toRelStructure.induce
        (activeCarrier A C e.toFunctionEmbedding)) := by
  classical
  let S := activeCarrier A C e.toFunctionEmbedding
  let inc : RelStructure.Embedding (C.toRelStructure.induce S)
      C.toRelStructure :=
    RelStructure.inclusion C.toRelStructure S
  constructor
  · intro x
    rcases x.2 with ⟨a, u, hu⟩
    let aS : RelStructure.Embedding A (C.toRelStructure.induce S) := {
      toFun := fun z => ⟨a.val z, projected_mem_activeCarrier A C
        e.toFunctionEmbedding a z⟩
      injective := by
        intro z w h
        apply a.val.injective
        exact congrArg Subtype.val h
      map_rel_iff := by
        intro R t
        change C.rel R (a.val ∘ t) ↔ A.rel R t
        exact a.val.map_rel_iff R t
    }
    refine ⟨aS, ?_⟩
    refine ⟨u, ?_⟩
    apply Subtype.ext
    exact hu
  · intro R t ht
    let T : Set S := Set.range t
    by_cases hTsub : T.Subsingleton
    · by_cases har : 0 < L.arity R
      · let i0 : Fin (L.arity R) := ⟨0, har⟩
        have hi0 : (t i0).1 ∈ S := (t i0).2
        rcases hi0 with ⟨a, u, hu⟩
        let aS : RelStructure.Embedding A (C.toRelStructure.induce S) := {
          toFun := fun z => ⟨a.val z, projected_mem_activeCarrier A C
            e.toFunctionEmbedding a z⟩
          injective := by
            intro z w h
            apply a.val.injective
            exact congrArg Subtype.val h
          map_rel_iff := by
            intro Q s
            change C.rel Q (a.val ∘ s) ↔ A.rel Q s
            exact a.val.map_rel_iff Q s
        }
        refine ⟨aS, ?_⟩
        intro i
        have hti : t i = t i0 := by
          apply hTsub
          · exact ⟨i, rfl⟩
          · exact ⟨i0, rfl⟩
        refine ⟨u, ?_⟩
        apply Subtype.ext
        change a.val u = (t i).1
        rw [hti]
        exact hu
      · rcases hActive with ⟨x, hx⟩
        rcases hx with ⟨a, _, _⟩
        let aS : RelStructure.Embedding A (C.toRelStructure.induce S) := {
          toFun := fun z => ⟨a.val z, projected_mem_activeCarrier A C
            e.toFunctionEmbedding a z⟩
          injective := by
            intro z w h
            apply a.val.injective
            exact congrArg Subtype.val h
          map_rel_iff := by
            intro Q s
            change C.rel Q (a.val ∘ s) ↔ A.rel Q s
            exact a.val.map_rel_iff Q s
        }
        refine ⟨aS, ?_⟩
        intro i
        exact (har (Nat.zero_lt_of_lt i.isLt)).elim
    · have hTIrr :
          ((C.toRelStructure.induce S).induce T).Irreducible := by
        intro x y hxy
        rcases x.2 with ⟨ix, hix⟩
        rcases y.2 with ⟨iy, hiy⟩
        have hixy : ix ≠ iy := by
          intro h
          apply hxy
          apply Subtype.ext
          rw [← hix, ← hiy, h]
        let z : Fin (L.arity R) → T :=
          fun i => ⟨t i, ⟨i, rfl⟩⟩
        refine ⟨R, z, ix, iy, ?_, ?_, ?_⟩
        · change (C.toRelStructure.induce S).rel R
            (Subtype.val ∘ z)
          convert ht using 1
          funext i
          rfl
        · apply Subtype.ext
          exact hix
        · apply Subtype.ext
          exact hiy
      let inclT :
          RelStructure.Embedding
            ((C.toRelStructure.induce S).induce T)
            C.toRelStructure :=
        inc.comp (RelStructure.inclusion
          (C.toRelStructure.induce S) T)
      let TRng : Set X := Set.range inclT
      have hTRngIrr :
          (C.toRelStructure.induce TRng).Irreducible :=
        hTIrr.range_embedding inclT
      obtain ⟨q, hq⟩ := hCover TRng hTRngIrr
      have hPartInE :
          ∀ i : Fin (L.arity R),
            C.part ((t i).1) ∈ copyCarrier e := by
        intro i
        exact activeCarrier_part_in_baseCopy A D C e (t i).2
      have hPartInB :
          ∀ i : Fin (L.arity R),
            C.part ((t i).1) ∈ copyCarrier q.base := by
        intro i
        have hmem : (t i).1 ∈ TRng := by
          exact ⟨⟨t i, ⟨i, rfl⟩⟩, rfl⟩
        obtain ⟨b, hb⟩ := hq ⟨(t i).1, hmem⟩
        refine ⟨b, ?_⟩
        calc
          q.base b = C.part (q.embedding b) := (q.projects b).symm
          _ = C.part ((t i).1) := congrArg C.part hb.symm
      have hPartNonSub :
          ¬ (copyCarrier e ∩ copyCarrier q.base).Subsingleton := by
        intro hs
        rw [Set.not_subsingleton_iff] at hTsub
        rcases hTsub with ⟨x, hxT, y, hyT, hxy⟩
        rcases hxT with ⟨ix, hix⟩
        rcases hyT with ⟨iy, hiy⟩
        have hxyVal : (t ix).1 ≠ (t iy).1 := by
          intro h
          apply hxy
          apply Subtype.ext
          simpa [hix, hiy] using h
        have hpartNe :
            C.part ((t ix).1) ≠ C.part ((t iy).1) := by
          intro hp
          apply hxyVal
          exact C.transversal R (Subtype.val ∘ t) ht ix iy hp
        apply hpartNe
        exact hs
          ⟨hPartInE ix, hPartInB ix⟩
          ⟨hPartInE iy, hPartInB iy⟩
      have hEsub :
          copyCarrier e ⊆ copyCarrier q.base :=
        hBaseStrong q.base q.base_mem e hPartNonSub
      have hFactor :
          ∀ a : UA, ∃ b : VB, e a = q.base b := by
        intro a
        rcases hEsub ⟨a, rfl⟩ with ⟨b, hb⟩
        exact ⟨b, hb.symm⟩
      let eB : RelStructure.Embedding A B :=
        e.factorThroughRange q.base hFactor
      have heB (a : UA) : e a = q.base (eB a) :=
        Classical.choose_spec (hFactor a)
      let aC : RelStructure.Embedding A C.toRelStructure :=
        q.embedding.comp eB
      have hTupleIn :
          ∀ i : Fin (L.arity R), (t i).1 ∈ copyCarrier aC := by
        intro i
        have hmem : (t i).1 ∈ TRng := by
          exact ⟨⟨t i, ⟨i, rfl⟩⟩, rfl⟩
        obtain ⟨b, hb⟩ := hq ⟨(t i).1, hmem⟩
        obtain ⟨a0, ha0⟩ := hPartInE i
        have hparts :
            q.base b = q.base (eB a0) := by
          calc
            q.base b = C.part (q.embedding b) := (q.projects b).symm
            _ = C.part ((t i).1) := congrArg C.part hb.symm
            _ = e a0 := ha0.symm
            _ = q.base (eB a0) := heB a0
        have hbEq : b = eB a0 := q.base.injective hparts
        refine ⟨a0, ?_⟩
        change q.embedding (eB a0) = (t i).1
        rw [← hbEq]
        exact hb.symm
      have hACsub : copyCarrier aC ⊆ S := by
        intro z hz
        rcases hz with ⟨a0, rfl⟩
        -- Every vertex of eB(A) projects to e(A), hence belongs to an active
        -- A-copy; use the copy aC itself with the prescribed projection e.
        refine ⟨⟨aC, ?_⟩, a0, rfl⟩
        intro a
        calc
          C.part (aC a) = q.base (eB a) := q.projects (eB a)
          _ = e a := (heB a).symm
      have hActiveFactor :
          ∀ a0 : UA, ∃ s : S, aC a0 = inc s := by
        intro a0
        exact ⟨⟨aC a0, hACsub ⟨a0, rfl⟩⟩, rfl⟩
      let aS' : RelStructure.Embedding A
          (C.toRelStructure.induce S) :=
        aC.factorThroughRange inc hActiveFactor
      have haS' (a0 : UA) : aC a0 = inc (aS' a0) :=
        Classical.choose_spec (hActiveFactor a0)
      refine ⟨aS', ?_⟩
      intro i
      rcases hTupleIn i with ⟨a0, ha0⟩
      refine ⟨a0, ?_⟩
      apply Subtype.ext
      simpa [inc] using (haS' a0).symm.trans ha0

end StructuralRamsey.Girth
