import Girth.ForestPermittedLeafGirth
import Mathlib.Tactic

/-!
# Every finite forest of A-supported B-pieces preserves ambient Berge girth

A join-tree forest has leaf deletions. The overlap between a leaf and
the whole rest is exactly its intersection with one parent, and the
allowed intersection property makes that overlap either a singleton
or a complete A-support edge. Thus the generic singleton/edge Berge
gluing lemmas allow girth to be reconstructed after leaf deletion.

Strong induction on the number of labelled pieces now proves that
the complete union of intrinsic A-support edge families has girth
greater than any given g whenever every member's support does.

This removes the need for a *separate* abstract girth hypothesis on
the finite B-copy forest generated by the selected pieces. It says
nothing about additional A-copies in the larger decorated ambient
relational structure, which require the actual picture geometry.
-/

namespace StructuralRamsey.Girth

universe v
variable {W : Type v}

/-- All member edges in any finite forest preserve the common
girth cutoff. The proof is a genuine induction over *different*
finite member-index types, not merely a fixed chosen leaf sequence. -/
theorem girthGT_union_of_forest
    {I : Type v} [Fintype I]
    (F : I → HypergraphPiece W)
    (hForest : ForestOfCopies F)
    (g : ℕ)
    (hEach : ∀ i : I, GirthGT (F i).edges g) :
    GirthGT (⋃ i : I, (F i).edges) g := by
  classical
  have hInd (n : ℕ) :
      ∀ (J : Type v) [Fintype J],
        Fintype.card J = n →
        ∀ (G : J → HypergraphPiece W),
          ForestOfCopies G →
          (∀ j : J, GirthGT (G j).edges g) →
          GirthGT (⋃ j : J, (G j).edges) g := by
    induction n using Nat.strong_induction_on with
    | h n ih =>
      intro J _ hCard G hG hPieces
      by_cases hNonempty : Nonempty J
      · letI : Nonempty J := hNonempty
        by_cases hSub : Subsingleton J
        · letI : Subsingleton J := hSub
          let j0 : J := Classical.choice hNonempty
          have hEdgesSub :
              (⋃ j : J, (G j).edges) ⊆ (G j0).edges := by
            intro e he
            obtain ⟨j, hj⟩ := Set.mem_iUnion.mp he
            have hjEq : j = j0 := Subsingleton.elim j j0
            simpa only [hjEq] using hj
          exact girthGT_of_subset hEdgesSub (hPieces j0)
        · have hDistinct : ∃ a b : J, a ≠ b := by
            by_contra hNo
            apply hSub
            refine ⟨?_⟩
            intro a b
            by_contra hab
            exact hNo ⟨a, b, hab⟩
          obtain ⟨a, b, hab⟩ := hDistinct
          letI : Nontrivial J := ⟨a, b, hab⟩
          obtain ⟨T⟩ := hG.joinTree_of_nonempty
          obtain ⟨leaf, parent, hadj, huniq, _hOverlap⟩ :=
            T.exists_leaf_attachment
          have hRestForest :
              ForestOfCopies (erasePiece G leaf) :=
            hG.erase_leaf T hadj huniq
          let J' := {j : J // j ∈ (({leaf} : Set J)ᶜ)}
          have hCardLt :
              Fintype.card J' < Fintype.card J := by
            apply Fintype.card_lt_of_injective_not_surjective
              (fun j : J' => j.1) Subtype.val_injective
            intro hSurj
            obtain ⟨j, hj⟩ := hSurj leaf
            have hNe : j.1 ≠ leaf := by
              simpa using j.2
            exact hNe hj
          have hRestGirth :
              GirthGT
                (⋃ j : {i : J // i ≠ leaf}, (G j.1).edges) g := by
            have hStep : GirthGT
                (⋃ j : J', (erasePiece G leaf j).edges) g := by
              apply ih (Fintype.card J')
              · omega
              · exact J'
              · rfl
              · exact erasePiece G leaf
              · exact hRestForest
              · intro j
                exact hPieces j.1
            simpa only [J', erasePiece, Set.mem_compl_iff,
              Set.mem_singleton_iff] using hStep
          exact T.girthGT_of_leaf_deletion
            hG.pairwiseAllowed hadj huniq g
            hRestGirth (hPieces leaf)
      · haveI : IsEmpty J := ⟨fun j => hNonempty ⟨j⟩⟩
        rintro ⟨c, _⟩
        have hlen : 0 < c.length := by omega
        have hEdge := c.edge_mem (⟨0, hlen⟩ : Fin c.length)
        obtain ⟨j, _⟩ := Set.mem_iUnion.mp hEdge
        exact isEmptyElim j
  exact hInd (Fintype.card I) I rfl F hForest hEach

end StructuralRamsey.Girth
