import Girth.MixedForest
import Girth.ForestEnumeration

/-! # Relational unions of mixed A/B forest members

The amalgamation union used in the manuscript is the relational union generated
by the selected members, not the full induced structure on their vertex union.
This file gives that construction for a heterogeneous family of A- and B-copies
and packages the free leaf decomposition.
-/

namespace StructuralRamsey.Girth

open StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {UA VB W ι X : Type v}

/-- Union of the carriers of a mixed family. -/
def mixedFamilyCarrier
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (m : ι → ABMember A B R) : Set W :=
  ⋃ i : ι, (m i).carrier

/-- Relational amalgamation union generated by a mixed family.  A tuple is
present exactly when it is an ambient tuple wholly contained in one selected
member. -/
def mixedFamilyUnionStructure
    {A : RelStructure L UA} {B : RelStructure L VB}
    (R : RelStructure L W)
    (m : ι → ABMember A B R) :
    RelStructure L (mixedFamilyCarrier m) where
  rel sym x :=
    R.rel sym (Subtype.val ∘ x) ∧
      ∃ i : ι, ∀ k, (x k).1 ∈ (m i).carrier

/-- Every selected mixed member embeds canonically into the generated union. -/
def mixedMemberEmbedding
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (m : ι → ABMember A B R) (i : ι) :
    Embedding (m i).source (mixedFamilyUnionStructure R m) where
  toFun x :=
    ⟨(m i).toAmbient x,
      Set.mem_iUnion.mpr ⟨i, ⟨x, rfl⟩⟩⟩
  injective := by
    intro x y h
    apply (m i).toAmbient.injective
    exact congrArg Subtype.val h
  map_rel_iff := by
    intro sym x
    constructor
    · intro h
      exact ((m i).toAmbient.map_rel_iff sym x).mp h.1
    · intro h
      refine ⟨((m i).toAmbient.map_rel_iff sym x).mpr h, ?_⟩
      refine ⟨i, ?_⟩
      intro k
      exact ⟨x k, rfl⟩

/-- An ambient A-copy contained in one mixed member embeds into the generated
union. -/
def aCopyToMixedFamilyUnion
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (m : ι → ABMember A B R)
    (a : Embedding A R) (i : ι)
    (hSub : copyCarrier a ⊆ (m i).carrier) :
    Embedding A (mixedFamilyUnionStructure R m) where
  toFun x :=
    ⟨a x, Set.mem_iUnion.mpr ⟨i, hSub ⟨x, rfl⟩⟩⟩
  injective := by
    intro x y h
    apply a.injective
    exact congrArg
      (fun z : mixedFamilyCarrier m => z.1) h
  map_rel_iff := by
    intro sym x
    constructor
    · intro h
      exact (a.map_rel_iff sym x).mp h.1
    · intro h
      refine ⟨(a.map_rel_iff sym x).mpr h, ?_⟩
      exact ⟨i, fun k => hSub ⟨x k, rfl⟩⟩

/-- Pointwise range witness for factoring an ambient A-copy through one mixed
member containing it. -/
theorem aCopyFactorIntoMixedMember_exists
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (c : ABMember A B R)
    (a : Embedding A R)
    (hSub : copyCarrier a ⊆ c.carrier)
    (x : UA) :
    ∃ y : c.VertexType, a x = c.toAmbient y := by
  rcases hSub ⟨x, rfl⟩ with ⟨y, hy⟩
  exact ⟨y, hy.symm⟩

/-- Factor a contained ambient A-copy through an arbitrary mixed member. -/
noncomputable def aCopyFactorIntoMixedMember
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (c : ABMember A B R)
    (a : Embedding A R)
    (hSub : copyCarrier a ⊆ c.carrier) :
    Embedding A c.source :=
  a.factorThroughRange c.toAmbient
    (aCopyFactorIntoMixedMember_exists c a hSub)

@[simp]
theorem aCopyFactorIntoMixedMember_spec
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (c : ABMember A B R)
    (a : Embedding A R)
    (hSub : copyCarrier a ⊆ c.carrier)
    (x : UA) :
    c.toAmbient (aCopyFactorIntoMixedMember c a hSub x) = a x := by
  change
    c.toAmbient
      (Classical.choose
        (aCopyFactorIntoMixedMember_exists c a hSub x)) = a x
  exact
    (Classical.choose_spec
      (aCopyFactorIntoMixedMember_exists c a hSub x)).symm

/-- If the index type has only one element, the mixed union embeds back into
that unique member. -/
noncomputable def mixedFamilyUnionToMember_of_subsingleton
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    [Subsingleton ι]
    (m : ι → ABMember A B R) (i : ι) :
    Embedding (mixedFamilyUnionStructure R m) (m i).source := by
  refine
    ((Iso.refl (mixedFamilyUnionStructure R m)).toEmbedding).factorThroughRange
      (mixedMemberEmbedding m i) ?_
  intro q
  rcases Set.mem_iUnion.mp q.2 with ⟨j, hqj⟩
  rcases hqj with ⟨y, hy⟩
  have hji : j = i := Subsingleton.elim _ _
  subst j
  refine ⟨y, ?_⟩
  apply Subtype.ext
  exact hy.symm

/-- For a leaf of a mixed join tree, intersection with the whole remaining
carrier union is exactly intersection with the unique parent. -/
theorem JoinTree.mixed_leaf_inter_rest_eq_parent
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    {m : ι → ABMember A B R}
    (J : JoinTree (fun i => (m i).supportPiece A))
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent) :
    (m leaf).carrier ∩
        mixedFamilyCarrier
          (fun j : {j : ι // j ≠ leaf} => m j.1) =
      (m leaf).carrier ∩ (m parent).carrier := by
  simpa [mixedFamilyCarrier, ABMember.supportPiece_carrier] using
    J.leaf_inter_iUnion_eq_parent hadj huniq

/-- The mixed union of all members except a leaf embeds inducedly into the
full mixed union. -/
def JoinTree.mixedRestToFullEmbedding
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    {m : ι → ABMember A B R}
    (J : JoinTree (fun i => (m i).supportPiece A))
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent) :
    Embedding
      (mixedFamilyUnionStructure R
        (fun j : {j : ι // j ≠ leaf} => m j.1))
      (mixedFamilyUnionStructure R m) where
  toFun := fun z => ⟨z.1, by
    rcases Set.mem_iUnion.mp z.2 with ⟨j, hzj⟩
    exact Set.mem_iUnion.mpr ⟨j.1, hzj⟩⟩
  injective := by
    intro x y h
    apply Subtype.ext
    exact congrArg
      (fun z : mixedFamilyCarrier m => z.1) h
  map_rel_iff := by
    intro sym x
    constructor
    · intro hFull
      refine ⟨hFull.1, ?_⟩
      rcases hFull.2 with ⟨i, hi⟩
      by_cases hil : i = leaf
      · subst i
        let p : {j : ι // j ≠ leaf} :=
          ⟨parent, hadj.ne.symm⟩
        refine ⟨p, ?_⟩
        intro k
        have hk :
            (x k).1 ∈
              (m leaf).carrier ∩
                mixedFamilyCarrier
                  (fun j : {j : ι // j ≠ leaf} => m j.1) :=
          ⟨hi k, (x k).2⟩
        rw [J.mixed_leaf_inter_rest_eq_parent hadj huniq] at hk
        exact hk.2
      · exact ⟨⟨i, hil⟩, hi⟩
    · intro hRest
      refine ⟨hRest.1, ?_⟩
      rcases hRest.2 with ⟨j, hj⟩
      exact ⟨j.1, hj⟩

/-- The generated mixed union is the free amalgam of the leaf-deleted union
and the leaf member over any structure that parametrizes exactly their common
vertices. -/
theorem JoinTree.mixedFamilyUnion_isFreeAmalgam_leaf_of_overlap
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    {m : ι → ABMember A B R}
    (J : JoinTree (fun i => (m i).supportPiece A))
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent)
    {D : Type v} (O : RelStructure L D)
    (fRest :
      Embedding O
        (mixedFamilyUnionStructure R
          (fun j : {j : ι // j ≠ leaf} => m j.1)))
    (fLeaf : Embedding O (m leaf).source)
    (hOverlap :
      ∀ q :
          mixedFamilyCarrier
            (fun j : {j : ι // j ≠ leaf} => m j.1),
        ∀ y : (m leaf).VertexType,
          q.1 = (m leaf).toAmbient y ↔
            ∃ d : D, q = fRest d ∧ y = fLeaf d) :
    IsFreeAmalgam
      fRest fLeaf
      (J.mixedRestToFullEmbedding hadj huniq)
      (mixedMemberEmbedding m leaf) := by
  classical
  constructor
  · intro z
    rcases Set.mem_iUnion.mp z.2 with ⟨i, hzi⟩
    by_cases hil : i = leaf
    · subst i
      rcases hzi with ⟨y, hy⟩
      exact Or.inr ⟨y, by apply Subtype.ext; exact hy.symm⟩
    · let j : {j : ι // j ≠ leaf} := ⟨i, hil⟩
      let q :
          mixedFamilyCarrier
            (fun j : {j : ι // j ≠ leaf} => m j.1) :=
        ⟨z.1, Set.mem_iUnion.mpr ⟨j, hzi⟩⟩
      exact Or.inl ⟨q, by apply Subtype.ext; rfl⟩
  · intro q y
    constructor
    · intro hqy
      have hv : q.1 = (m leaf).toAmbient y := by
        exact congrArg
          (fun z : mixedFamilyCarrier m => z.1) hqy
      exact (hOverlap q y).mp hv
    · intro h
      have hv : q.1 = (m leaf).toAmbient y :=
        (hOverlap q y).mpr h
      apply Subtype.ext
      exact hv
  · intro sym z
    constructor
    · intro hz
      rcases hz.2 with ⟨i, hi⟩
      by_cases hil : i = leaf
      · subst i
        let pre : Fin (L.arity sym) → (m leaf).VertexType :=
          fun k => Classical.choose (hi k)
        have hpre (k : Fin (L.arity sym)) :
            (m leaf).toAmbient (pre k) = (z k).1 :=
          Classical.choose_spec (hi k)
        have htuple :
            (m leaf).toAmbient.toFun ∘ pre =
              Subtype.val ∘ z := by
          funext k
          exact hpre k
        have hLeafRel : (m leaf).source.rel sym pre := by
          apply ((m leaf).toAmbient.map_rel_iff sym pre).mp
          rw [htuple]
          exact hz.1
        refine Or.inr ⟨pre, hLeafRel, ?_⟩
        funext k
        apply Subtype.ext
        exact (hpre k).symm
      · let j : {j : ι // j ≠ leaf} := ⟨i, hil⟩
        let x :
            Fin (L.arity sym) →
              mixedFamilyCarrier
                (fun j : {j : ι // j ≠ leaf} => m j.1) :=
          fun k =>
            ⟨(z k).1, Set.mem_iUnion.mpr ⟨j, hi k⟩⟩
        have hxrel :
            (mixedFamilyUnionStructure R
              (fun j : {j : ι // j ≠ leaf} => m j.1)).rel sym x := by
          exact ⟨hz.1, ⟨j, fun k => hi k⟩⟩
        refine Or.inl ⟨x, hxrel, ?_⟩
        funext k
        apply Subtype.ext
        rfl
    · rintro (⟨x, hx, hz⟩ | ⟨x, hx, hz⟩)
      · have hmap :=
          ((J.mixedRestToFullEmbedding hadj huniq).map_rel_iff sym x).mpr hx
        rw [hz]
        exact hmap
      · have hmap :=
          ((mixedMemberEmbedding m leaf).map_rel_iff sym x).mpr hx
        rw [hz]
        exact hmap

end StructuralRamsey.Girth
