import Mathlib.Combinatorics.SimpleGraph.Acyclic

/-! # Ranked parent graphs

A rooted parent relation in which every non-root vertex points to a strictly
lower natural-number rank defines a tree.  Connectivity follows by repeatedly
following parents.  For acyclicity, rotate an alleged cycle to a vertex of
maximum rank; both cycle neighbours would then have to be that vertex's unique
parent.
-/

namespace StructuralRamsey.Girth

universe v
variable {V : Type v}

/-- The undirected graph generated by the parent relation. -/
def rankedParentGraph
    (root : V) (parent : V → V) : SimpleGraph V :=
  SimpleGraph.fromRel
    (fun v w => v ≠ root ∧ parent v = w)

@[simp]
theorem rankedParentGraph_adj
    (root : V) (parent : V → V) (v w : V) :
    (rankedParentGraph root parent).Adj v w ↔
      v ≠ w ∧
        ((v ≠ root ∧ parent v = w) ∨
          (w ≠ root ∧ parent w = v)) := by
  simp [rankedParentGraph]

/-- Every vertex reaches the root by repeatedly following the parent. -/
theorem rankedParentGraph_reachable_root
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v)
    (v : V) :
    (rankedParentGraph root parent).Reachable v root := by
  by_cases hv : v = root
  · subst v
    exact SimpleGraph.Reachable.refl _
  · have hne : v ≠ parent v := by
      intro h
      have hd := hDrop v hv
      rw [← h] at hd
      exact (Nat.lt_irrefl _ hd)
    have hadj :
        (rankedParentGraph root parent).Adj
          v (parent v) := by
      rw [rankedParentGraph_adj]
      exact ⟨hne, Or.inl ⟨hv, rfl⟩⟩
    exact
      hadj.reachable.trans
        (rankedParentGraph_reachable_root
          root parent rank hDrop (parent v))
termination_by rank v
decreasing_by
  exact hDrop v hv

/-- A ranked parent graph is connected. -/
theorem rankedParentGraph_connected
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v) :
    (rankedParentGraph root parent).Connected := by
  letI : Nonempty V := ⟨root⟩
  refine ⟨?_⟩
  intro a b
  exact
    (rankedParentGraph_reachable_root
      root parent rank hDrop a).trans
      (rankedParentGraph_reachable_root
        root parent rank hDrop b).symm

/-- A ranked parent graph is acyclic. -/
theorem rankedParentGraph_isAcyclic
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v) :
    (rankedParentGraph root parent).IsAcyclic := by
  classical
  intro v c hc
  have hs : c.support.toFinset.Nonempty := by
    exact ⟨v, by simp⟩
  obtain ⟨m, hmFin, hmax⟩ :=
    Finset.exists_max_image c.support.toFinset rank hs
  have hm : m ∈ c.support := by
    simpa using hmFin
  let q := c.rotate m hm
  have hq : q.IsCycle := hc.rotate hm
  have hnon : ¬q.Nil := hq.not_nil
  have hsndQ : q.snd ∈ q.support :=
    List.mem_of_mem_tail (q.snd_mem_tail_support hnon)
  have hpenQ : q.penultimate ∈ q.support :=
    List.mem_of_mem_dropLast
      (q.penultimate_mem_dropLast_support hnon)
  have hsndC : q.snd ∈ c.support :=
    (SimpleGraph.Walk.mem_support_rotate_iff c m hm).mp hsndQ
  have hpenC : q.penultimate ∈ c.support :=
    (SimpleGraph.Walk.mem_support_rotate_iff c m hm).mp hpenQ
  have hsndLe : rank q.snd ≤ rank m :=
    hmax q.snd (by simpa using hsndC)
  have hpenLe : rank q.penultimate ≤ rank m :=
    hmax q.penultimate (by simpa using hpenC)
  have neighbor_eq_parent
      (n : V)
      (hadj : (rankedParentGraph root parent).Adj m n)
      (hnle : rank n ≤ rank m) :
      n = parent m := by
    rcases (rankedParentGraph_adj root parent m n).mp hadj with
      ⟨_hne, hmn | hnm⟩
    · exact hmn.2.symm
    · have hd := hDrop n hnm.1
      rw [hnm.2] at hd
      omega
  have hsnd :
      q.snd = parent m :=
    neighbor_eq_parent q.snd (q.adj_snd hnon) hsndLe
  have hpen :
      q.penultimate = parent m :=
    neighbor_eq_parent q.penultimate
      (q.adj_penultimate hnon).symm hpenLe
  exact hq.snd_ne_penultimate (hsnd.trans hpen.symm)

/-- A ranked parent graph is a tree. -/
theorem rankedParentGraph_isTree
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v) :
    (rankedParentGraph root parent).IsTree where
  connected :=
    rankedParentGraph_connected root parent rank hDrop
  isAcyclic :=
    rankedParentGraph_isAcyclic root parent rank hDrop

end StructuralRamsey.Girth
