import Mathlib.Combinatorics.SimpleGraph.Acyclic

/-! # Ranked parent graphs

A finite rooted parent relation in which every non-root vertex points to a
strictly lower natural-number rank defines a tree.  This packages the generic
graph-theoretic step needed when contracting the vertex side of an incidence
forest toward a chosen root.
-/

namespace StructuralRamsey.Girth

universe v
variable {V : Type v}

/-- The undirected graph generated by the parent relation. -/
def rankedParentGraph
    (root : V) (parent : V → V) : SimpleGraph V :=
  SimpleGraph.fromRel
    (fun v w => v ≠ root ∧ parent v = w)

@[simp]
theorem rankedParentGraph_adj
    (root : V) (parent : V → V) (v w : V) :
    (rankedParentGraph root parent).Adj v w ↔
      v ≠ w ∧
        ((v ≠ root ∧ parent v = w) ∨
          (w ≠ root ∧ parent w = v)) := by
  simp [rankedParentGraph]

/-- The canonical edge contributed by a non-root vertex. -/
def rankedParentEdge
    (root : V) (parent : V → V)
    (v : {v : V // v ≠ root})
    (hParentNe : ∀ x : V, x ≠ root → parent x ≠ x) :
    (rankedParentGraph root parent).edgeSet :=
  ⟨s(v.1, parent v.1), by
    rw [SimpleGraph.mem_edgeSet, rankedParentGraph_adj]
    exact
      ⟨hParentNe v.1 v.2,
        Or.inl ⟨v.2, rfl⟩⟩⟩

/-- Rank drop excludes the two-cycle ambiguity in the parent-edge map. -/
theorem rankedParentEdge_injective
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v) :
    Function.Injective
      (rankedParentEdge root parent
        (fun v hv => ne_of_lt (hDrop v hv))) := by
  intro v w h
  apply Subtype.ext
  change v.1 = w.1
  have hedge :
      s(v.1, parent v.1) =
        s(w.1, parent w.1) :=
    congrArg Subtype.val h
  rw [Sym2.eq_iff] at hedge
  rcases hedge with hsame | hswap
  · exact hsame.1
  · have hvw : v.1 = parent w.1 := hswap.1
    have hpvw : parent v.1 = w.1 := hswap.2
    have hvDrop := hDrop v.1 v.2
    have hwDrop := hDrop w.1 w.2
    rw [hvw, hpvw] at hvDrop hwDrop
    omega

/-- Every edge of the parent graph is contributed by a non-root vertex. -/
theorem rankedParentEdge_surjective
    (root : V) (parent : V → V)
    (hParentNe : ∀ x : V, x ≠ root → parent x ≠ x) :
    Function.Surjective
      (rankedParentEdge root parent hParentNe) := by
  intro e
  rcases e with ⟨e, he⟩
  induction e using Sym2.inductionOn with
  | _ a b =>
      rw [SimpleGraph.mem_edgeSet, rankedParentGraph_adj] at he
      rcases he.2 with h | h
      · refine ⟨⟨a, h.1⟩, ?_⟩
        apply Subtype.ext
        rw [Sym2.eq_iff]
        exact Or.inl ⟨rfl, h.2.symm⟩
      · refine ⟨⟨b, h.1⟩, ?_⟩
        apply Subtype.ext
        rw [Sym2.eq_iff]
        exact Or.inr ⟨h.2.symm, rfl⟩

/-- Every vertex reaches the root by repeatedly following the parent. -/
theorem rankedParentGraph_reachable_root
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v)
    (v : V) :
    (rankedParentGraph root parent).Reachable v root := by
  classical
  induction h : rank v using Nat.strong_induction_on generalizing v with
  | h n ih =>
      by_cases hv : v = root
      · subst v
        exact SimpleGraph.Reachable.refl _
      · have hadj :
            (rankedParentGraph root parent).Adj
              v (parent v) := by
          rw [rankedParentGraph_adj]
          exact
            ⟨ne_of_lt (hDrop v hv),
              Or.inl ⟨hv, rfl⟩⟩
        have hrec :
            (rankedParentGraph root parent).Reachable
              (parent v) root := by
          apply ih (rank (parent v)) (hDrop v hv) (parent v)
          rfl
        exact hadj.reachable.trans hrec

/-- A ranked parent graph is connected. -/
theorem rankedParentGraph_connected
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v) :
    (rankedParentGraph root parent).Connected := by
  refine ⟨?_⟩
  intro a b
  exact
    (rankedParentGraph_reachable_root
      root parent rank hDrop a).trans
      (rankedParentGraph_reachable_root
        root parent rank hDrop b).symm

/-- A finite ranked parent graph is a tree. -/
theorem rankedParentGraph_isTree
    [Fintype V]
    (root : V) (parent : V → V) (rank : V → ℕ)
    (hDrop : ∀ v : V, v ≠ root → rank (parent v) < rank v) :
    (rankedParentGraph root parent).IsTree := by
  classical
  let G := rankedParentGraph root parent
  have hConn : G.Connected :=
    rankedParentGraph_connected root parent rank hDrop
  apply SimpleGraph.isTree_of_connected_card_edgeFinset G hConn
  have hParentNe :
      ∀ x : V, x ≠ root → parent x ≠ x :=
    fun x hx => ne_of_lt (hDrop x hx)
  let f :
      {v : V // v ≠ root} →
        G.edgeSet :=
    rankedParentEdge root parent hParentNe
  have hfbij : Function.Bijective f :=
    ⟨rankedParentEdge_injective
        root parent rank hDrop,
      rankedParentEdge_surjective
        root parent hParentNe⟩
  have hcardEdges :
      Fintype.card G.edgeSet =
        Fintype.card {v : V // v ≠ root} :=
    Fintype.card_congr
      (Equiv.ofBijective f hfbij) |>.symm
  have hcardSubtype :
      Fintype.card {v : V // v ≠ root} + 1 =
        Fintype.card V := by
    simpa using
      Fintype.card_subtype_compl
        (p := fun v : V => v = root)
  rw [G.edgeFinset_card, hcardEdges]
  exact hcardSubtype

end StructuralRamsey.Girth
