import Girth.RelationalUnionFreeAmalgam
import Girth.TreeSupport
import Girth.ForestEnumeration

/-! # Relational unions indexed by a forest of B-copies

For the forest-to-supported-tree-amalgam argument we distinguish the union
structure generated by the selected copies from the full ambient induced
substructure.  A relation tuple belongs to the union structure exactly when
it is an ambient relation tuple contained in one selected member.
-/

namespace StructuralRamsey.Girth

open StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {UA VB W ι : Type v}

/-- The union of the image carriers of a labelled family of B-copies. -/
def familyCarrier
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) : Set W :=
  ⋃ i : ι, copyCarrier (b i)

/-- The relational union generated by a labelled family of copies. -/
def familyUnionStructure
    {B : RelStructure L VB} (R : RelStructure L W)
    (b : ι → Embedding B R) :
    RelStructure L (familyCarrier b) where
  rel sym x :=
    R.rel sym (Subtype.val ∘ x) ∧
      ∃ i : ι, ∀ k, (x k).1 ∈ copyCarrier (b i)

/-- Every selected member embeds canonically into the relational union. -/
def familyMemberEmbedding
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) (i : ι) :
    Embedding B (familyUnionStructure R b) where
  toFun x :=
    ⟨b i x, Set.mem_iUnion.mpr ⟨i, ⟨x, rfl⟩⟩⟩
  injective := by
    intro x y h
    apply (b i).injective
    exact congrArg Subtype.val h
  map_rel_iff := by
    intro sym x
    constructor
    · intro h
      exact ((b i).map_rel_iff sym x).mp h.1
    · intro h
      refine ⟨((b i).map_rel_iff sym x).mpr h, ?_⟩
      refine ⟨i, ?_⟩
      intro k
      exact ⟨x k, rfl⟩

/-- Regard only the carrier of an embedded copy as a hypergraph piece. -/
def embeddingCarrierPiece
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : Embedding B R) : HypergraphPiece W where
  carrier := copyCarrier b
  edges := ∅
  edge_subset_carrier := by
    intro e he
    simp at he

/-- An ambient A-copy contained in one selected B-member embeds into the
relational union generated by the family. -/
def aCopyToFamilyUnion
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (b : ι → Embedding B R)
    (a : Embedding A R) (i : ι)
    (hSub : copyCarrier a ⊆ copyCarrier (b i)) :
    Embedding A (familyUnionStructure R b) where
  toFun x :=
    ⟨a x, Set.mem_iUnion.mpr ⟨i, hSub ⟨x, rfl⟩⟩⟩
  injective := by
    intro x y h
    apply a.injective
    exact congrArg
      (fun z : familyCarrier b => z.1) h
  map_rel_iff := by
    intro sym x
    constructor
    · intro h
      exact (a.map_rel_iff sym x).mp h.1
    · intro h
      refine ⟨(a.map_rel_iff sym x).mpr h, ?_⟩
      refine ⟨i, ?_⟩
      intro k
      exact hSub ⟨x k, rfl⟩

/-- Pointwise range witness for factoring a contained A-copy through a
B-member. -/
theorem aCopyFactorIntoMember_exists
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (a : Embedding A R) (b : Embedding B R)
    (hSub : copyCarrier a ⊆ copyCarrier b)
    (x : UA) :
    ∃ y : VB, a x = b y := by
  rcases hSub ⟨x, rfl⟩ with ⟨y, hy⟩
  exact ⟨y, hy.symm⟩

/-- Factor an ambient A-copy through a B-member containing its whole carrier. -/
noncomputable def aCopyFactorIntoMember
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (a : Embedding A R) (b : Embedding B R)
    (hSub : copyCarrier a ⊆ copyCarrier b) :
    Embedding A B :=
  a.factorThroughRange b
    (aCopyFactorIntoMember_exists a b hSub)

@[simp]
theorem aCopyFactorIntoMember_spec
    {A : RelStructure L UA} {B : RelStructure L VB}
    {R : RelStructure L W}
    (a : Embedding A R) (b : Embedding B R)
    (hSub : copyCarrier a ⊆ copyCarrier b)
    (x : UA) :
    b (aCopyFactorIntoMember a b hSub x) = a x := by
  change
    b (Classical.choose
      (aCopyFactorIntoMember_exists a b hSub x)) = a x
  exact
    (Classical.choose_spec
      (aCopyFactorIntoMember_exists a b hSub x)).symm

/-- The empty structure carrying the ambient nullary relation data of R. -/
def ambientEmpty
    (R : RelStructure L W) :
    RelStructure L PEmpty where
  rel sym x := R.rel sym (fun k => PEmpty.elim (x k))

/-- The ambient empty structure embeds into any structure already embedded in
the ambient structure.  This keeps nullary relations correct without assuming
that the language has positive arity. -/
def ambientEmptyToMember
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : Embedding B R) :
    Embedding (ambientEmpty R) B where
  toFun d := PEmpty.elim d
  injective := by
    intro d
    exact PEmpty.elim d
  map_rel_iff := by
    intro sym x
    let y : Fin (L.arity sym) → VB :=
      fun k => PEmpty.elim (x k)
    have htuple :
        b.toFun ∘ y = (fun k => PEmpty.elim (x k)) := by
      funext k
      exact PEmpty.elim (x k)
    change
      B.rel sym y ↔
        R.rel sym (fun k => PEmpty.elim (x k))
    rw [← htuple]
    exact (b.map_rel_iff sym y).symm

/-- The ambient empty structure embeds into a member-generated union through
any chosen family member. -/
def ambientEmptyToFamilyUnion
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) (i : ι) :
    Embedding (ambientEmpty R) (familyUnionStructure R b) :=
  (familyMemberEmbedding b i).comp
    (ambientEmptyToMember (b i))

/-- The one-point structure induced by the ambient relational type of x. -/
def ambientPoint
    (R : RelStructure L W) (x : W) :
    RelStructure L PUnit where
  rel sym _ := R.rel sym (fun _ => x)

/-- If an A-copy sends a position a to x, and another A-copy in a target
structure represents the same chosen A-position data, the ambient one-point
type at x embeds at that target position. -/
def ambientPointEmbedding
    {A : RelStructure L UA}
    {R : RelStructure L W} {X : Type v}
    {T : RelStructure L X}
    (alphaR : Embedding A R)
    (alphaT : Embedding A T)
    (a : UA) (x : W)
    (hx : alphaR a = x) :
    Embedding (ambientPoint R x) T where
  toFun := fun _ => alphaT a
  injective := by
    intro p q _
    exact Subsingleton.elim p q
  map_rel_iff := by
    intro sym z
    change
      T.rel sym ((fun _ : PUnit => alphaT a) ∘ z) ↔
        R.rel sym (fun _ => x)
    have hTtuple :
        ((fun _ : PUnit => alphaT a) ∘ z) =
          (alphaT.toFun ∘ (fun _ : Fin (L.arity sym) => a)) := by
      funext k
      rfl
    have hRtuple :
        (fun _ : Fin (L.arity sym) => x) =
          (alphaR.toFun ∘ (fun _ : Fin (L.arity sym) => a)) := by
      funext k
      exact hx.symm
    rw [hTtuple, hRtuple]
    exact
      (alphaT.map_rel_iff sym (fun _ => a)).trans
        (alphaR.map_rel_iff sym (fun _ => a)).symm

/-- Allowed overlap types for two full B-members in the supported-tree
conversion: empty, a whole ambient A-copy, or a singleton supported inside
both incident B-copies. -/
def SupportedBCopyOverlap
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    (b₁ b₂ : Embedding B R) : Prop :=
  copyCarrier b₁ ∩ copyCarrier b₂ = ∅ ∨
    (∃ a : Embedding A R,
      copyCarrier b₁ ∩ copyCarrier b₂ = copyCarrier a) ∨
    ∃ x : W,
      copyCarrier b₁ ∩ copyCarrier b₂ = {x} ∧
      VertexSupportedInBCopy A b₁ x ∧
      VertexSupportedInBCopy A b₂ x

/-- Pairwise supported overlap for a labelled family of B-copies. -/
def PairwiseSupportedBCopyOverlap
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) : Prop :=
  ∀ ⦃i j : ι⦄, i ≠ j →
    SupportedBCopyOverlap A (b i) (b j)

/-- The supported-overlap predicate is symmetric. -/
theorem supportedBCopyOverlap_symm
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    {b₁ b₂ : Embedding B R}
    (h : SupportedBCopyOverlap A b₁ b₂) :
    SupportedBCopyOverlap A b₂ b₁ := by
  rcases h with hEmpty | hCopy | hPoint
  · left
    simpa [Set.inter_comm] using hEmpty
  · right
    left
    rcases hCopy with ⟨a, ha⟩
    exact ⟨a, by simpa [Set.inter_comm] using ha⟩
  · right
    right
    rcases hPoint with ⟨x, hx, hs₁, hs₂⟩
    exact ⟨x, by simpa [Set.inter_comm] using hx, hs₂, hs₁⟩

/-- A join tree on the full copy carriers. -/
abbrev BCopyJoinTree
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) :=
  JoinTree (fun i => embeddingCarrierPiece (b i))

/-- Removing a leaf from a full-carrier join tree leaves exactly the parent
intersection as the leaf's intersection with the union of all remaining
member carriers. -/
theorem BCopyJoinTree.leaf_inter_rest_eq_parent
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (J : BCopyJoinTree b)
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent) :
    copyCarrier (b leaf) ∩
        familyCarrier (fun j : {j : ι // j ≠ leaf} => b j.1) =
      copyCarrier (b leaf) ∩ copyCarrier (b parent) := by
  simpa [familyCarrier, embeddingCarrierPiece] using
    J.leaf_inter_iUnion_eq_parent hadj huniq

/-- The pairwise supported-overlap hypothesis is inherited by deleting one
label. -/
theorem pairwiseSupportedBCopyOverlap_erase
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (h : PairwiseSupportedBCopyOverlap A b)
    (leaf : ι) :
    PairwiseSupportedBCopyOverlap A
      (fun j : {j : ι // j ≠ leaf} => b j.1) := by
  intro i j hij
  apply h
  intro hval
  apply hij
  exact Subtype.ext hval


/-- The relational union of all members except a leaf embeds inducedly into
the full member-generated union.  The only reflection case needing the join
tree is a relation witnessed by the deleted leaf: all of its tuple vertices
already lie in the rest union, hence the leaf/rest intersection identity
places them in the parent member. -/
def BCopyJoinTree.restToFullEmbedding
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (J : BCopyJoinTree b)
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent) :
    Embedding
      (familyUnionStructure R
        (fun j : {j : ι // j ≠ leaf} => b j.1))
      (familyUnionStructure R b) where
  toFun := fun z => ⟨z.1, by
    rcases Set.mem_iUnion.mp z.2 with ⟨j, hzj⟩
    exact Set.mem_iUnion.mpr ⟨j.1, hzj⟩⟩
  injective := by
    intro x y h
    apply Subtype.ext
    exact congrArg
      (fun z : familyCarrier b => z.1) h
  map_rel_iff := by
    intro sym x
    constructor
    · intro hFull
      refine ⟨hFull.1, ?_⟩
      rcases hFull.2 with ⟨i, hi⟩
      by_cases hil : i = leaf
      · subst i
        let p : {j : ι // j ≠ leaf} :=
          ⟨parent, hadj.ne.symm⟩
        refine ⟨p, ?_⟩
        intro k
        have hk :
            (x k).1 ∈
              copyCarrier (b leaf) ∩
                familyCarrier
                  (fun j : {j : ι // j ≠ leaf} => b j.1) :=
          ⟨hi k, (x k).2⟩
        rw [J.leaf_inter_rest_eq_parent hadj huniq] at hk
        exact hk.2
      · let p : {j : ι // j ≠ leaf} := ⟨i, hil⟩
        exact ⟨p, hi⟩
    · intro hRest
      refine ⟨hRest.1, ?_⟩
      rcases hRest.2 with ⟨j, hj⟩
      exact ⟨j.1, hj⟩


/-- The full member-generated union is the free amalgam of the leaf-deleted
union and the leaf copy over any overlap structure that parametrizes exactly
their common vertices. -/
theorem BCopyJoinTree.familyUnion_isFreeAmalgam_leaf_of_overlap
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (J : BCopyJoinTree b)
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent)
    {D : Type v} (O : RelStructure L D)
    (fRest :
      Embedding O
        (familyUnionStructure R
          (fun j : {j : ι // j ≠ leaf} => b j.1)))
    (fLeaf : Embedding O B)
    (hOverlap :
      ∀ a :
          familyCarrier
            (fun j : {j : ι // j ≠ leaf} => b j.1),
        ∀ y : VB,
          a.1 = b leaf y ↔
            ∃ d : D, a = fRest d ∧ y = fLeaf d) :
    IsFreeAmalgam
      fRest fLeaf
      (J.restToFullEmbedding hadj huniq)
      (familyMemberEmbedding b leaf) := by
  classical
  constructor
  · intro z
    rcases Set.mem_iUnion.mp z.2 with ⟨i, hzi⟩
    by_cases hil : i = leaf
    · subst i
      rcases hzi with ⟨y, hy⟩
      refine Or.inr ⟨y, ?_⟩
      apply Subtype.ext
      exact hy.symm
    · let j : {j : ι // j ≠ leaf} := ⟨i, hil⟩
      let a :
          familyCarrier
            (fun j : {j : ι // j ≠ leaf} => b j.1) :=
        ⟨z.1, Set.mem_iUnion.mpr ⟨j, hzi⟩⟩
      refine Or.inl ⟨a, ?_⟩
      apply Subtype.ext
      rfl
  · intro a y
    constructor
    · intro hay
      have hv : a.1 = b leaf y := by
        exact congrArg
          (fun z : familyCarrier b => z.1) hay
      exact (hOverlap a y).mp hv
    · intro h
      have hv : a.1 = b leaf y :=
        (hOverlap a y).mpr h
      apply Subtype.ext
      exact hv
  · intro sym z
    constructor
    · intro hz
      rcases hz.2 with ⟨i, hi⟩
      by_cases hil : i = leaf
      · subst i
        let pre : Fin (L.arity sym) → VB :=
          fun k => Classical.choose (hi k)
        have hpre (k : Fin (L.arity sym)) :
            b leaf (pre k) = (z k).1 :=
          Classical.choose_spec (hi k)
        have htuple :
            (b leaf).toFun ∘ pre = Subtype.val ∘ z := by
          funext k
          exact hpre k
        have hBrel : B.rel sym pre := by
          apply ((b leaf).map_rel_iff sym pre).mp
          rw [htuple]
          exact hz.1
        refine Or.inr ⟨pre, hBrel, ?_⟩
        funext k
        apply Subtype.ext
        exact (hpre k).symm
      · let j : {j : ι // j ≠ leaf} := ⟨i, hil⟩
        let x :
            Fin (L.arity sym) →
              familyCarrier
                (fun j : {j : ι // j ≠ leaf} => b j.1) :=
          fun k =>
            ⟨(z k).1, Set.mem_iUnion.mpr ⟨j, hi k⟩⟩
        have hxrel :
            (familyUnionStructure R
              (fun j : {j : ι // j ≠ leaf} => b j.1)).rel sym x := by
          refine ⟨?_, ⟨j, ?_⟩⟩
          · exact hz.1
          · intro k
            exact hi k
        refine Or.inl ⟨x, hxrel, ?_⟩
        funext k
        apply Subtype.ext
        rfl
    · rintro (⟨x, hx, hz⟩ | ⟨x, hx, hz⟩)
      · have hmap :=
          ((J.restToFullEmbedding hadj huniq).map_rel_iff sym x).mpr hx
        rw [hz]
        exact hmap
      · have hmap :=
          ((familyMemberEmbedding b leaf).map_rel_iff sym x).mpr hx
        rw [hz]
        exact hmap

end StructuralRamsey.Girth
