import Girth.RelationalUnionFreeAmalgam
import Girth.TreeSupport
import Girth.ForestEnumeration

/-! # Relational unions indexed by a forest of B-copies

For the forest-to-supported-tree-amalgam argument we distinguish the union
structure generated by the selected copies from the full ambient induced
substructure.  A relation tuple belongs to the union structure exactly when
it is an ambient relation tuple contained in one selected member.
-/

namespace StructuralRamsey.Girth

open StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {UA VB W ι : Type v}

/-- The union of the image carriers of a labelled family of B-copies. -/
def familyCarrier
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) : Set W :=
  ⋃ i : ι, copyCarrier (b i)

/-- The relational union generated by a labelled family of copies. -/
def familyUnionStructure
    {B : RelStructure L VB} (R : RelStructure L W)
    (b : ι → Embedding B R) :
    RelStructure L (familyCarrier b) where
  rel sym x :=
    R.rel sym (Subtype.val ∘ x) ∧
      ∃ i : ι, ∀ k, (x k).1 ∈ copyCarrier (b i)

/-- Every selected member embeds canonically into the relational union. -/
def familyMemberEmbedding
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) (i : ι) :
    Embedding B (familyUnionStructure R b) where
  toFun x :=
    ⟨b i x, Set.mem_iUnion.mpr ⟨i, ⟨x, rfl⟩⟩⟩
  injective := by
    intro x y h
    apply (b i).injective
    exact congrArg Subtype.val h
  map_rel_iff := by
    intro sym x
    constructor
    · intro h
      exact ((b i).map_rel_iff sym x).mp h.1
    · intro h
      refine ⟨((b i).map_rel_iff sym x).mpr h, ?_⟩
      refine ⟨i, ?_⟩
      intro k
      exact ⟨x k, rfl⟩

/-- Regard only the carrier of an embedded copy as a hypergraph piece. -/
def embeddingCarrierPiece
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : Embedding B R) : HypergraphPiece W where
  carrier := copyCarrier b
  edges := ∅
  edge_subset_carrier := by
    intro e he
    exact (Set.not_mem_empty e he).elim

/-- Allowed overlap types for two full B-members in the supported-tree
conversion: empty, a whole ambient A-copy, or a singleton supported inside
both incident B-copies. -/
def SupportedBCopyOverlap
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    (b₁ b₂ : Embedding B R) : Prop :=
  copyCarrier b₁ ∩ copyCarrier b₂ = ∅ ∨
    (∃ a : Embedding A R,
      copyCarrier b₁ ∩ copyCarrier b₂ = copyCarrier a) ∨
    ∃ x : W,
      copyCarrier b₁ ∩ copyCarrier b₂ = {x} ∧
      VertexSupportedInBCopy A b₁ x ∧
      VertexSupportedInBCopy A b₂ x

/-- Pairwise supported overlap for a labelled family of B-copies. -/
def PairwiseSupportedBCopyOverlap
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) : Prop :=
  ∀ ⦃i j : ι⦄, i ≠ j →
    SupportedBCopyOverlap A (b i) (b j)

/-- The supported-overlap predicate is symmetric. -/
theorem supportedBCopyOverlap_symm
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    {b₁ b₂ : Embedding B R}
    (h : SupportedBCopyOverlap A b₁ b₂) :
    SupportedBCopyOverlap A b₂ b₁ := by
  rcases h with hEmpty | hCopy | hPoint
  · left
    simpa [Set.inter_comm] using hEmpty
  · right
    left
    rcases hCopy with ⟨a, ha⟩
    exact ⟨a, by simpa [Set.inter_comm] using ha⟩
  · right
    right
    rcases hPoint with ⟨x, hx, hs₁, hs₂⟩
    exact ⟨x, by simpa [Set.inter_comm] using hx, hs₂, hs₁⟩

/-- A join tree on the full copy carriers. -/
abbrev BCopyJoinTree
    {B : RelStructure L VB} {R : RelStructure L W}
    (b : ι → Embedding B R) :=
  JoinTree (fun i => embeddingCarrierPiece (b i))

/-- Removing a leaf from a full-carrier join tree leaves exactly the parent
intersection as the leaf's intersection with the union of all remaining
member carriers. -/
theorem BCopyJoinTree.leaf_inter_rest_eq_parent
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (J : BCopyJoinTree b)
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent) :
    copyCarrier (b leaf) ∩
        familyCarrier (fun j : {j : ι // j ≠ leaf} => b j.1) =
      copyCarrier (b leaf) ∩ copyCarrier (b parent) := by
  simpa [familyCarrier, embeddingCarrierPiece] using
    J.leaf_inter_iUnion_eq_parent hadj huniq

/-- The pairwise supported-overlap hypothesis is inherited by deleting one
label. -/
theorem pairwiseSupportedBCopyOverlap_erase
    (A : RelStructure L UA)
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (h : PairwiseSupportedBCopyOverlap A b)
    (leaf : ι) :
    PairwiseSupportedBCopyOverlap A
      (fun j : {j : ι // j ≠ leaf} => b j.1) := by
  intro i j hij
  apply h
  intro hval
  apply hij
  exact Subtype.ext hval


/-- The relational union of all members except a leaf embeds inducedly into
the full member-generated union.  The only reflection case needing the join
tree is a relation witnessed by the deleted leaf: all of its tuple vertices
already lie in the rest union, hence the leaf/rest intersection identity
places them in the parent member. -/
def BCopyJoinTree.restToFullEmbedding
    {B : RelStructure L VB} {R : RelStructure L W}
    {b : ι → Embedding B R}
    (J : BCopyJoinTree b)
    {leaf parent : ι}
    (hadj : J.tree.Adj leaf parent)
    (huniq : ∀ j : ι, J.tree.Adj leaf j → j = parent) :
    Embedding
      (familyUnionStructure R
        (fun j : {j : ι // j ≠ leaf} => b j.1))
      (familyUnionStructure R b) where
  toFun := fun z => ⟨z.1, by
    rcases Set.mem_iUnion.mp z.2 with ⟨j, hzj⟩
    exact Set.mem_iUnion.mpr ⟨j.1, hzj⟩⟩
  injective := by
    intro x y h
    apply Subtype.ext
    exact congrArg
      (fun z : familyCarrier b => z.1) h
  map_rel_iff := by
    intro sym x
    constructor
    · intro hFull
      refine ⟨hFull.1, ?_⟩
      rcases hFull.2 with ⟨i, hi⟩
      by_cases hil : i = leaf
      · subst i
        let p : {j : ι // j ≠ leaf} :=
          ⟨parent, hadj.ne.symm⟩
        refine ⟨p, ?_⟩
        intro k
        have hk :
            (x k).1 ∈
              copyCarrier (b leaf) ∩
                familyCarrier
                  (fun j : {j : ι // j ≠ leaf} => b j.1) :=
          ⟨hi k, (x k).2⟩
        rw [J.leaf_inter_rest_eq_parent hadj huniq] at hk
        exact hk.2
      · let p : {j : ι // j ≠ leaf} := ⟨i, hil⟩
        exact ⟨p, hi⟩
    · intro hRest
      refine ⟨hRest.1, ?_⟩
      rcases hRest.2 with ⟨j, hj⟩
      exact ⟨j.1, hj⟩

end StructuralRamsey.Girth
